ok- well heres what happened. i forgot i deleted all the previous scenarios out of the game  so when i tried playing the game, it threw an error that there were no scenarios. understandable. so i put new scenarios in, reset the game and this error popped up but only one player nicks side. jakes side is fine so far.
should i just reset again and try again?

Error: A <Select.Item /> must have a value prop that is not an empty string. This is because the Select value can be set to an empty string to clear the selection and show the placeholder.
    at SelectItem (https://9000-firebase-studio-1748385878962.cluster-joak5ukfbnbyqspg4tewa33d24.cloudworkstations.dev/_next/static/chunks/node_modules_9f33c105._.js:19803:15)
    at _c8 (https://9000-firebase-studio-1748385878962.cluster-joak5ukfbnbyqspg4tewa33d24.cloudworkstations.dev/_next/static/chunks/src_199dfddd._.js:615:461)
    at https://9000-firebase-studio-1748385878962.cluster-joak5ukfbnbyqspg4tewa33d24.cloudworkstations.dev/_next/static/chunks/src_199dfddd._.js:996:290
    at Array.map (<anonymous>)
    at JudgeView (https://9000-firebase-studio-1748385878962.cluster-joak5ukfbnbyqspg4tewa33d24.cloudworkstations.dev/_next/static/chunks/src_199dfddd._.js:996:72)
    at renderGameContent (https://9000-firebase-studio-1748385878962.cluster-joak5ukfbnbyqspg4tewa33d24.cloudworkstations.dev/_next/static/chunks/src_199dfddd._.js:3735:222)
    at GamePage (https://9000-firebase-studio-1748385878962.cluster-joak5ukfbnbyqspg4tewa33d24.cloudworkstations.dev/_next/static/chunks/src_199dfddd._.js:3870:21)
    at ClientPageRoot (https://9000-firebase-studio-1748385878962.cluster-joak5ukfbnbyqspg4tewa33d24.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)